-d U:\home\renato\faculdade\26.1-sistemasembarcados\drs\dr1\tp3\dr1_tp3\impl\gwsynthesis\dr1_tp3.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst U:\home\renato\faculdade\26.1-sistemasembarcados\drs\dr1\tp3\dr1_tp3\src\constraints.cst
-cfg U:\home\renato\faculdade\26.1-sistemasembarcados\drs\dr1\tp3\dr1_tp3\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
