-d C:\Users\Renat\Desktop\DRs\dr1\tp2\tp2_tang_nano_9k\impl\gwsynthesis\tp2_tang_nano_9k.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\Renat\Desktop\DRs\dr1\tp2\tp2_tang_nano_9k\src\tp2_tang_nano_9k.cst
-cfg C:\Users\Renat\Desktop\DRs\dr1\tp2\tp2_tang_nano_9k\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
