-d \\wsl.localhost\Ubuntu\home\renato\faculdade\26.1-sistemasembarcados\drs\dr3\tp2\gowin\impl\gwsynthesis\tp2_sequence_validator.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst \\wsl.localhost\Ubuntu\home\renato\faculdade\26.1-sistemasembarcados\drs\dr3\tp2\gowin\src\tp2_sequence_validator.cst
-cfg \\wsl.localhost\Ubuntu\home\renato\faculdade\26.1-sistemasembarcados\drs\dr3\tp2\gowin\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
